### ISSUE TITLE
文件缺失-可以帮忙看看吗

### ISSUE THREAD

**Issue by lamaxiyasit** [PolarisRisingWar/LJP_Collection#1]
data = pk.load(open(os.path.join(args.data_folder, mode + '_processed_thulac_Legal_basis.pkl'), 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ruan/Projects/LJP_Collection/models/NeurJudge/CAIL2018_LADAN/train_processed_thulac_Legal_basis.pkl'

**Comment by PolarisRisingWar** [comment]
数据集的预处理可以参考LADAN的原GitHub项目，这块我还没整理代码。你也可以自己改改用自己的数据格式

**Comment by lamaxiyasit** [comment]
同学您好 我研究的方式是ljp的 但是代码复现比较困难（ljp比较小众，可用资源比较少同时不少代码复现比较难） 请问有什么好的建议吗

**Comment by PolarisRisingWar** [comment]
原则上我写这个GitHub项目就是给出了这个问题的答案

**Comment by cy330874054** [comment]
作者你好，对于NeurJudge有基于bert编码器的实现吗

**Comment by PolarisRisingWar** [comment]
> 作者你好，对于NeurJudge有基于bert编码器的实现吗

暂时还没有，以后可以补

**Comment by PolarisRisingWar** [comment]
LADAN格式的数据集更新了

**Comment by ttingCui** [comment]
> LADAN格式的数据集更新了

LADAN的small数据集分享链接好像过期了，可以再分享一下吗，谢谢

**Comment by PolarisRisingWar** [comment]
> > LADAN格式的数据集更新了
> 
> LADAN的small数据集分享链接好像过期了，可以再分享一下吗，谢谢

更新了
