### ISSUE TITLE
太感谢了！！！！wang 同学你这个Repo简直是最让人惊喜的贡献

### ISSUE THREAD

**Issue by SimonYS001** [PolarisRisingWar/LJP_Collection#4]
你这个Repo简直太棒了！，不过还是想问一个简单的问题，

Textcnn, TOPJUDGE 里的超参为啥是空着的？ 还有就是DataAdapterDataset类的构造函数为什么也是略？求指教

**Comment by SimonYS001** [comment]
超参是不是可以看LADAN的统计数据，然后DataAdapterDataset是不是可以参考NeurJudge的train_and_test.py？

**Comment by PolarisRisingWar** [comment]
超参和构造函数空着是因为涉及隐私信息。这两项都可以根据你采用的具体数据集和数据格式进行自定义，反正整体的模型代码我已经写好了。

**Comment by SimonYS001** [comment]
了解了，非常感谢，你的Review什么时候出炉？我要怎么reference你的贡献😄

**Comment by PolarisRisingWar** [comment]
论文还在路上，刚刚在README中更新了引用GitHub仓库的参考写法。
如果你的论文限制引用在线资源，也可以直接在脚注中引用链接。

**Comment by SimonYS001** [comment]
谢谢，我会加进去的
