### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by winnerLuo** [PolarisRisingWar/LJP_Collection#5]
你好，这几天一直在PBFN中的代码发现构造函数中的略，根据之前的回复，我在其中间加入了LADAN中的train_processed_thulac.pkl文件，如下图所示
![GitHub](https://github.com/PolarisRisingWar/LJP_Collection/assets/70368328/15e1041c-8576-40ac-9f58-a39ba2432c5b)
会出现    sentence = case.strip().split()
AttributeError: 'numpy.ndarray' object has no attribute 'strip'错误。请问是文件不对吗，您所说的数据集是哪一种，有相关数据下载链接么。

**Comment by PolarisRisingWar** [comment]
这个fact_list是文本列表，每个元素是用空格隔开的分词后的原文
